name: flutterturizm
description: "Flutter Turizm Uygulaması"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2

  # database
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  firebase_auth: ^4.17.4
  firebase_storage: ^11.6.11
  google_sign_in: ^6.2.1
  firebase_database: ^10.5.1

  # core
  kartal: ^3.5.0
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  connectivity_plus: ^3.0.2
  internet_connection_checker: ^1.0.0+1
  data_connection_checker_nulls: ^0.0.2
  cached_network_image: ^3.3.1
  http: ^1.2.1
  intl_phone_field: ^3.2.0
  pretty_qr_code: ^3.3.0
  qr: ^3.0.1
  qr_flutter: ^4.1.0
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  


  # utility
  animated_text_kit: ^4.2.2
  loading_animation_widget: ^1.2.0+4
  hexcolor: ^3.0.1
  contained_tab_bar_view: ^0.8.0
  google_fonts: ^4.0.4
  carousel_slider: ^4.2.1
  logger: ^2.0.2
  url_launcher: ^6.1.6
  animate_do: ^3.1.2
  flutter_datetime_picker_plus: ^2.1.0
  intl: ^0.18.1
  material_design_icons_flutter: ^7.0.7296
  percent_indicator: ^4.2.3
  flutter_map: ^6.1.0
  flutter_rating_bar: ^4.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.7.1
  build_runner: ^2.4.8


  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true


  assets:
    # logo images
    - assets/images/app_img/
    # login / register / password icons
    - assets/icons/logregpass_icons/
    # login / register / password images
    - assets/images/logregpass_img/
    # tickets images
    - assets/images/tickets_img/
    # tickets icons
    - assets/icons/tickets_icons/
    # live support images
    - assets/images/livesupport_img/
    # profile icons
    - assets/icons/profile_icons/
    # connection error images
    - assets/images/connectionerror_img/
 

